### ISSUE TITLE
[v.2.134.0] Error on first command run, after server start only: /ah

### ISSUE THREAD

**Issue by smscentras** [kiranhart/Auction-House#106]
Purpur 1.21.1
AuctionHouse v2.134.0
Error on first command run, after server start only: /ah

```
[03:52:28] [Server thread/INFO]: Administrator issued server command: /ah
[03:52:29] [Server thread/ERROR]: Command exception: /ah
org.bukkit.command.CommandException: Unhandled exception executing command 'ah' in plugin AuctionHouse v2.134.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Unknown standard bukkit form: ENTITY_GOAT_SCREAMING_HORN_BREAK named ENTITY_GOAT_SCREAMING_HORN_BREAK
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.utils.base.XRegistry.std(XRegistry.java:302) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.utils.base.XRegistry.std(XRegistry.java:288) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.utils.base.XRegistry.pullSystemValues(XRegistry.java:123) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.utils.base.XRegistry.pullValues(XRegistry.java:86) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.utils.base.XRegistry.getByName(XRegistry.java:219) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.comp.enums.CompSound.matchCompSound(CompSound.java:1819) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.guis.AuctionUpdatingPagedGUI.applyDefaults(AuctionUpdatingPagedGUI.java:167) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.guis.AuctionUpdatingPagedGUI.<init>(AuctionUpdatingPagedGUI.java:55) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.guis.core.GUIAuctionHouse.<init>(GUIAuctionHouse.java:52) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.guis.core.GUIAuctionHouse.<init>(GUIAuctionHouse.java:75) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.commands.CommandAuctionHouse.execute(CommandAuctionHouse.java:62) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.command.CommandManager.processRequirements(CommandManager.java:331) ~[AuctionHouse - v2.134.0.jar:?]
	at AuctionHouse - v2.134.0.jar/ca.tweetzy.auctionhouse.flight.command.CommandManager.onCommand(CommandManager.java:231) ~[AuctionHouse - v2.134.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 27 more
```

**Comment by smscentras** [comment]
v2.133.0 - all ok
